appId: com.seb.green
productName: Green Design System
directories:
  output: dist
files:
  - src/**/*
  - assets/**/*
  - package.json
mac:
  category: public.app-category.developer-tools
  icon: assets/gds.icns
  target:
    - dmg
    - zip
win:
  icon: assets/gds.ico
  target:
    - nsis
    - portable
linux:
  icon: assets/gds.png
  target:
    - AppImage
    - deb
