name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Windows
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build:win

  release-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Build MacOS
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
          APPLE_ID: ""
          APPLE_APP_SPECIFIC_PASSWORD: ""
          CSC_LINK: ""
          CSC_KEY_PASSWORD: ""
          MAC_SIGNING: false
        run: |
          export CSC_IDENTITY_AUTO_DISCOVERY=false
          npx electron-builder build --mac -p always --config.mac.identity=null
